# 全局配置项
global: 
  resolve_timeout: 5h #处理超时时间，默认为5min
  smtp_smarthost: 'smtp.qq.com:465' # 邮箱smtp服务器代理，这里给出了QQ邮箱的host
  smtp_from: 'youremail@qq.com' # 发送邮箱名称
  smtp_auth_username: 'youremail@qq.com' # 邮箱名称
  smtp_auth_password: '***' # 邮箱密码或授权码
  smtp_require_tls: false


# 定义模板信心
templates:
  - 'template/*.tmpl'

# 定义路由树信息
route:
  group_by: ['alertname'] # 报警分组依据
  group_wait: 10s # 最初即第一次等待多久时间发送一组警报的通知
  group_interval: 5h # 在发送新警报前的等待时间
  repeat_interval: 5h # 发送重复警报的周期 对于email配置中，此项不可以设置过低，否则将会由于邮件发送太多频繁，被smtp服务器拒绝
  receiver: 'email' # 发送警报的接收者的名称，以下receivers name的名称

# 定义警报接收者信息
receivers:
  - name: 'email' # 警报
    email_configs: # 邮箱配置
    - to: 'yourreceiver@qq.com'  # 接收警报的email配置
      html: '{{ template "email.default.html" . }}' # 设定邮箱的内容模板
      headers: { Subject: "[WARN] 报警邮件"} # 接收邮件的标题
